### PR TITLE
Improves ui of login and create account pages, displays error messages for invalid login/account creation

### PR DESCRIPTION
**Pull request by kibby111701**

### CODE REVIEW

**Review by benlyon03 — COMMENTED** [review]
Awesome job Chris! Looks like you figured out how to make sure the same username could not be used. Can you explain to me how lines 131-135 in backend.js work? Mainly what does the .end() mean?

**Comment by kibby111701** [comment]
> Awesome job Chris! Looks like you figured out how to make sure the same username could not be used. Can you explain to me how lines 131-135 in backend.js work? Mainly what does the .end() mean?

131-135 are checking for specific errors in the create account, where one of them is looking for standard user errors (empty username or password) while the other looks for if the username is already taken. That way the app gives more detailed error messages for if the user can't create an account. The .end() is just sending back the error codes without any actual data as opposed to the .send() sending back a whole new user

**Review by BerkeleyReynolds — APPROVED** [review]
Looks good. The new UI for the login and create account pages looks great

**Review by shaikh7860 — APPROVED** [review]
Awesome work Chris! I love the new UI of the login page.

**Review by benlyon03 — APPROVED** [review]

**Pull request merged**
