### PR TITLE
fixed cookie error and changed the video to trailer

### PR DESCRIPTION
**Pull request by benlyon03**
This code fixes the error where it would send the user back to login after trying to search directly after logging in. This code also fixes the issue where the video played was not a trailer but the most recent video related to the movie.

### CODE REVIEW

**Review by kibby111701 — COMMENTED** [review]
No comments, looks good

**Review by shaikh7860 — APPROVED** [review]
Looks good!

**Review by BerkeleyReynolds — COMMENTED** [review]
Looks good, but I have a question -- how did you select which video from youtube will be played as the trailer for a movie?

**Comment by benlyon03** [comment]
> Looks good, but I have a question -- how did you select which video from youtube will be played as the trailer for a movie?

Hey Berkeley, the way I was able to choose the correct trailer for the movie took me filtering the json object we received from the movie database by trailers and then return the first results key.

**Comment by BerkeleyReynolds** [comment]
> > Looks good, but I have a question -- how did you select which video from youtube will be played as the trailer for a movie?
> 
> Hey Berkeley, the way I was able to choose the correct trailer for the movie took me filtering the json object we received from the movie database by trailers and then return the first results key.

Ah I see, nice. Good job, looks good!

**Review by BerkeleyReynolds — APPROVED** [review]
Looks good

**Review by kibby111701 — APPROVED** [review]
No comments, looks good

**Pull request merged**
