### PR TITLE
User search + friends list

### PR DESCRIPTION
**Pull request by kibby111701**

### CODE REVIEW

**Comment by kibby111701** [comment]
Still disables buttons for pushing movies and friends to favorites/friends lists, haven't made it so that they are removed

**Review by benlyon03 — COMMENTED** [review]
Hey Chris! Everything looks fantastic. I love how you decided to also implement the friends list to the site. 
The one bug that is currently occurring is when I favorite a movies, the release date includes the word "undefined". Just wanted to give you a heads up and it should be fixed before merged to new_main!

**Review by shaikh7860 — APPROVED** [review]
Looks awesome!

**Comment by BerkeleyReynolds** [comment]
The new friends feature looks great.
I will look into the unfavorite/unfriend features now

**Review by BerkeleyReynolds — APPROVED** [review]
Looks great

**Comment by kibby111701** [comment]
Just got the release dates bug fixed, with that I'll merge it in

**Pull request merged**
