### PR TITLE
UI of Error Page and Profile Page updated

### PR DESCRIPTION
**Pull request by shaikh7860**
I updated the user interface of the error page and profile page. For the profile page I updated the layout and improved the visual representation of the information.

### CODE REVIEW

**Review by benlyon03 — APPROVED** [review]
Looks good Ali! Can you specify what you ended up changing to the UI of the Profile page?

**Review by kibby111701 — APPROVED** [review]
Looks good to me! I like the addition of adding a link to home from the error page.

**Comment by shaikh7860** [comment]
> Looks good Ali! Can you specify what you ended up changing to the UI of the Profile page?

Thanks! I updated the pull request description.

**Comment by BerkeleyReynolds** [comment]
Looks good, I like the new additions to the UI

**Review by BerkeleyReynolds — APPROVED** [review]
Looks good, I like the new additions to the UI

**Pull request merged**
